"""Starter placeholder for transfer learning experiments.
Team member can extend this to run ResNet50 / other pretrained backbones on the same split CSVs.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
print("Use train/val/test split CSV files from results/tables/ generated by data_loader.py")
print(ROOT / "results" / "tables")
